<a href="https://colab.research.google.com/github/ErSKS/AI/blob/master/01_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing Numpy, Keras and its optimizers

In [ ]:
import numpy as np
from numpy.random import random

import keras
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import SGD

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [ ]:
x = random((20,1))
x

array([[0.92311537],
       [0.81631009],
       [0.01910849],
       [0.89364207],
       [0.35955744],
       [0.58069642],
       [0.52663084],
       [0.17406007],
       [0.48148889],
       [0.37600145],
       [0.88244908],
       [0.66492984],
       [0.97980167],
       [0.21010525],
       [0.68648837],
       [0.16362981],
       [0.09470291],
       [0.04564541],
       [0.87574116],
       [0.35631103]])

 ## y = 2 * x + 2


In [ ]:
y = np.dot(x, 2.) + 2.

#### Showing Values of X

In [ ]:
x

array([[0.92311537],
       [0.81631009],
       [0.01910849],
       [0.89364207],
       [0.35955744],
       [0.58069642],
       [0.52663084],
       [0.17406007],
       [0.48148889],
       [0.37600145],
       [0.88244908],
       [0.66492984],
       [0.97980167],
       [0.21010525],
       [0.68648837],
       [0.16362981],
       [0.09470291],
       [0.04564541],
       [0.87574116],
       [0.35631103]])

#### Showing Values of Y

In [ ]:
y

array([[3.84623075],
       [3.63262018],
       [2.03821697],
       [3.78728414],
       [2.71911487],
       [3.16139284],
       [3.05326169],
       [2.34812013],
       [2.96297778],
       [2.75200289],
       [3.76489815],
       [3.32985969],
       [3.95960335],
       [2.42021049],
       [3.37297673],
       [2.32725962],
       [2.18940582],
       [2.09129082],
       [3.75148233],
       [2.71262206]])

#### In Keras Sequential Means a Model which is like seqeuntial stack of layers. Its just something Keras uses to create models.

#### In addition to this Keras, uses Dense method to create a linear model, which is what we are going to use in our linear problem

In [ ]:
linear_model = Sequential()

In [ ]:
linear_model.add(Dense(1, input_shape=(1,)))

Here the first argument of Dense is the required  output dimension we required, here as the output is 1 dimensional array, we use 1. And as the input is also 1 dimensional we use 1

Then we call Compile method to the linear model we created with required Gradient descent Algorithm, Learning Rate and Loss function

Here, SGD is used for optimizer with learning rate of 0.1 and MSE or Mean Squared Loss as Loss function

In [ ]:
linear_model.compile(optimizer=SGD(lr=0.01), loss='mse')

This compile method first initializes weights with random values which is far from correct values

If we evaluate or check the Y predictions now with the random values, we will get result of Loss Function very large

In [ ]:
linear_model.evaluate(x, y)

20/20 [==============================] - 1s 36ms/step


6.692396640777588

To calculate weights with given input/output pair, we have to call fit() method on our model

In [ ]:
linear_model.fit(x,y, epochs=200, batch_size=5)

Epoch 1/200
20/20 [==============================] - 0s 17ms/step - loss: 6.2102
Epoch 2/200
20/20 [==============================] - 0s 450us/step - loss: 5.0484
Epoch 3/200
20/20 [==============================] - 0s 600us/step - loss: 4.1025
Epoch 4/200
20/20 [==============================] - 0s 600us/step - loss: 3.3343
Epoch 5/200
20/20 [==============================] - 0s 550us/step - loss: 2.7126
Epoch 6/200
20/20 [==============================] - 0s 550us/step - loss: 2.2034
Epoch 7/200
20/20 [==============================] - 0s 600us/step - loss: 1.7920
Epoch 8/200
20/20 [==============================] - 0s 450us/step - loss: 1.4572
Epoch 9/200
20/20 [==============================] - 0s 500us/step - loss: 1.1839
Epoch 10/200
20/20 [==============================] - 0s 550us/step - loss: 0.9623
Epoch 11/200
20/20 [==============================] - 0s 450us/step - loss: 0.7823
Epoch 12/200
20/20 [==============================] - 0s 500us/step - loss: 0.6368
Epoch 13/200
2

20/20 [==============================] - 0s 500us/step - loss: 5.4908e-06
Epoch 98/200
20/20 [==============================] - 0s 450us/step - loss: 5.4124e-06
Epoch 99/200
20/20 [==============================] - 0s 600us/step - loss: 5.3660e-06
Epoch 100/200
20/20 [==============================] - 0s 450us/step - loss: 5.2724e-06
Epoch 101/200
20/20 [==============================] - 0s 550us/step - loss: 5.2034e-06
Epoch 102/200
20/20 [==============================] - 0s 450us/step - loss: 5.1589e-06
Epoch 103/200
20/20 [==============================] - 0s 650us/step - loss: 5.1032e-06
Epoch 104/200
20/20 [==============================] - 0s 751us/step - loss: 5.0405e-06
Epoch 105/200
20/20 [==============================] - 0s 550us/step - loss: 4.9740e-06
Epoch 106/200
20/20 [==============================] - 0s 450us/step - loss: 4.8867e-06
Epoch 107/200
20/20 [==============================] - 0s 450us/step - loss: 4.8409e-06
Epoch 108/200
20/20 [===========================

20/20 [==============================] - 0s 450us/step - loss: 1.7252e-06
Epoch 191/200
20/20 [==============================] - 0s 400us/step - loss: 1.7039e-06
Epoch 192/200
20/20 [==============================] - 0s 450us/step - loss: 1.6859e-06
Epoch 193/200
20/20 [==============================] - 0s 500us/step - loss: 1.6656e-06
Epoch 194/200
20/20 [==============================] - 0s 400us/step - loss: 1.6377e-06
Epoch 195/200
20/20 [==============================] - 0s 400us/step - loss: 1.6230e-06
Epoch 196/200
20/20 [==============================] - 0s 350us/step - loss: 1.5946e-06
Epoch 197/200
20/20 [==============================] - 0s 400us/step - loss: 1.5756e-06
Epoch 198/200
20/20 [==============================] - 0s 500us/step - loss: 1.5560e-06
Epoch 199/200
20/20 [==============================] - 0s 600us/step - loss: 1.5428e-06
Epoch 200/200
20/20 [==============================] - 0s 550us/step - loss: 1.5194e-06


Here epochs is the number of epochs the calculation/learning should be run. 1 Epoch means going through each input ones... so 5 Epoch means going through all the inputs 5 times. 

Generally input data is fed in batches/collection, which are like 10-100 input data at onces, not all of them at once

Now if we check the loss value, it will be lot less than before

#### This is a title

In [ ]:
linear_model.evaluate(x, y, verbose=0)

1.5041637198009994e-06

We can only check the weights, the model has calculated

In [ ]:
linear_model.get_weights()

[array([[1.9961387]], dtype=float32), array([2.002116], dtype=float32)]

here 1.9411 is nearly equal to correct value which is 2, and the bias 2.0368 which is close to 2.0